// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Integration tests for iseriser.
// Tests the full pipeline: manifest -> validation -> scaffold -> output.

use iseriser::codegen::parser::validate_language_description;
use iseriser::codegen::scaffold::scaffold_repo;
use iseriser::manifest::{parse_manifest, validate};
use tempfile::tempdir;

// ---------------------------------------------------------------------------
// Helper: build a manifest TOML string from parameters
// ---------------------------------------------------------------------------

fn make_toml(
    lang_name: &str,
    paradigm: &str,
    type_sys: &str,
    target: &str,
    primitives: &[&str],
) -> String {
    let iser_name = format!("{}iser", lang_name.to_lowercase());
    let prims: Vec<String> = primitives.iter().map(|p| format!("\"{}\"", p)).collect();
    format!(
        r#"
[project]
name = "{iser_name}"
version = "0.1.0"

[language]
name = "{lang_name}"
paradigm = "{paradigm}"
type-system = "{type_sys}"
compilation-target = "{target}"
key-primitives = [{primitives}]

[output]
repo-name = "{iser_name}"
github-org = "hyperpolymath"
description = "{lang_name} interop -iser — generated by iseriser"
"#,
        iser_name = iser_name,
        lang_name = lang_name,
        paradigm = paradigm,
        type_sys = type_sys,
        target = target,
        primitives = prims.join(", "),
    )
}

// ---------------------------------------------------------------------------
// Test 1: Full pipeline for an imperative/native language (Chapel)
// ---------------------------------------------------------------------------

#[test]
fn test_full_pipeline_chapel() {
    let toml = make_toml(
        "Chapel",
        "imperative",
        "simple",
        "native",
        &["task", "locale", "domain", "forall", "sync"],
    );
    let manifest = parse_manifest(&toml).expect("parse failed");
    validate(&manifest).expect("structural validation failed");

    let report = validate_language_description(&manifest);
    assert!(
        report.is_valid(),
        "semantic validation failed: {:?}",
        report.errors
    );

    let tmp = tempdir().unwrap();
    let result = scaffold_repo(&manifest, tmp.path());
    assert!(
        result.is_success(),
        "scaffold failed: {:?}",
        result.error_message()
    );

    let repo = result.repo().unwrap();
    assert_eq!(repo.name, "chapeliser");
    assert!(
        repo.is_complete(),
        "generated repo missing mandatory categories"
    );
    assert!(
        repo.file_count() >= 20,
        "expected 20+ files, got {}",
        repo.file_count()
    );

    // Verify key files exist on disk
    let root = tmp.path().join("chapeliser");
    assert!(root.join("Cargo.toml").exists(), "Cargo.toml missing");
    assert!(root.join("src/main.rs").exists(), "src/main.rs missing");
    assert!(
        root.join("src/interface/abi/Chapeliser/ABI/Types.idr")
            .exists(),
        "Types.idr missing"
    );
    assert!(
        root.join("src/interface/abi/chapeliser-abi.ipkg").exists(),
        "chapeliser-abi.ipkg missing"
    );
    assert!(
        root.join("ffi/zig/src/main.zig").exists(),
        "main.zig missing"
    );
    assert!(root.join("README.adoc").exists(), "README.adoc missing");
    assert!(root.join("TOPOLOGY.md").exists(), "TOPOLOGY.md missing");

    // Verify Cargo.toml content
    let cargo = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(cargo.contains("chapeliser"), "Cargo.toml missing repo name");
    assert!(cargo.contains("MPL-2.0"), "Cargo.toml missing license");
}

// ---------------------------------------------------------------------------
// Test 2: Functional / BEAM language (Gleam)
// ---------------------------------------------------------------------------

#[test]
fn test_full_pipeline_gleam_functional_beam() {
    let toml = make_toml(
        "Gleam",
        "functional",
        "algebraic",
        "beam",
        &["result", "option", "dynamic"],
    );
    let manifest = parse_manifest(&toml).unwrap();
    validate(&manifest).unwrap();

    let tmp = tempdir().unwrap();
    let result = scaffold_repo(&manifest, tmp.path());
    assert!(result.is_success());

    let repo = result.repo().unwrap();
    assert_eq!(repo.name, "gleamiser");
    assert!(repo.is_complete());

    // Functional paradigm should generate ADT mapper
    assert!(
        repo.files
            .iter()
            .any(|f| f.path.to_str().unwrap().contains("adt_mapper")),
        "functional language should have adt_mapper"
    );

    // BEAM target should generate NIF boilerplate
    assert!(
        repo.files
            .iter()
            .any(|f| f.path.to_str().unwrap().contains("beam_nif")),
        "BEAM target should have beam_nif"
    );
}

// ---------------------------------------------------------------------------
// Test 3: Array language with deep type system (Julia)
// ---------------------------------------------------------------------------

#[test]
fn test_full_pipeline_julia_array() {
    let toml = make_toml(
        "Julia",
        "array",
        "gradual",
        "native",
        &["array", "broadcast", "multiple-dispatch"],
    );
    let manifest = parse_manifest(&toml).unwrap();
    validate(&manifest).unwrap();

    let tmp = tempdir().unwrap();
    let result = scaffold_repo(&manifest, tmp.path());
    assert!(result.is_success());

    let repo = result.repo().unwrap();
    assert_eq!(repo.name, "juliaiser");

    // Array paradigm should generate array bridge
    assert!(
        repo.files
            .iter()
            .any(|f| f.path.to_str().unwrap().contains("array_bridge")),
        "array language should have array_bridge"
    );
}

// ---------------------------------------------------------------------------
// Test 4: Dependent types language (Idris2-to-Idris2, meta!)
// ---------------------------------------------------------------------------

#[test]
fn test_full_pipeline_dependent_types() {
    let toml = make_toml(
        "Idris2",
        "functional",
        "dependent",
        "native",
        &["Nat", "Vect", "DPair"],
    );
    let manifest = parse_manifest(&toml).unwrap();
    validate(&manifest).unwrap();

    let tmp = tempdir().unwrap();
    let result = scaffold_repo(&manifest, tmp.path());
    assert!(result.is_success());

    let repo = result.repo().unwrap();

    // Dependent types should generate deep ABI proof docs
    assert!(
        repo.files
            .iter()
            .any(|f| f.path.to_str().unwrap().contains("deep-abi-proofs")),
        "dependent type language should have deep ABI proof docs"
    );

    // Verify the generated ABI ships the real machine-checked proof module
    // (the C-ABI compliance theorem), which superseded the old vacuous
    // `DeepProof` stub. This theorem is non-vacuous: it pins each field offset
    // via `DivideBy k Refl`, so a misaligned layout fails to typecheck.
    let proofs_idr = repo
        .files
        .iter()
        .find(|f| f.path.to_str().unwrap().contains("Proofs.idr"))
        .expect("Proofs.idr should be generated");
    assert!(
        proofs_idr.content.contains("CABICompliant"),
        "Proofs.idr should contain the C-ABI compliance theorem"
    );
}

// ---------------------------------------------------------------------------
// Test 5: Validation rejects invalid primitives
// ---------------------------------------------------------------------------

#[test]
fn test_validation_rejects_empty_primitive() {
    let toml = make_toml("BadLang", "functional", "algebraic", "native", &["ok", ""]);
    let manifest = parse_manifest(&toml).unwrap();
    let report = validate_language_description(&manifest);
    assert!(!report.is_valid(), "should reject empty primitive");
}

// ---------------------------------------------------------------------------
// Test 6: Validation warns on unusual paradigm/target combos
// ---------------------------------------------------------------------------

#[test]
fn test_validation_warns_logic_gpu() {
    let toml = make_toml("WeirdProlog", "logic", "none", "gpu", &["clause"]);
    let manifest = parse_manifest(&toml).unwrap();
    let report = validate_language_description(&manifest);
    assert!(
        report.is_valid(),
        "unusual combo should be a warning, not error"
    );
    assert!(
        !report.warnings.is_empty(),
        "should have warnings for logic+gpu"
    );
}

// ---------------------------------------------------------------------------
// Test 7: JS target generates JS bridge
// ---------------------------------------------------------------------------

#[test]
fn test_js_target_generates_bridge() {
    let toml = make_toml(
        "ReScript",
        "functional",
        "algebraic",
        "js",
        &["variant", "record", "promise"],
    );
    let manifest = parse_manifest(&toml).unwrap();
    validate(&manifest).unwrap();

    let tmp = tempdir().unwrap();
    let result = scaffold_repo(&manifest, tmp.path());
    assert!(result.is_success());

    let repo = result.repo().unwrap();
    assert!(
        repo.files
            .iter()
            .any(|f| f.path.to_str().unwrap().contains("js_bridge")),
        "JS target should generate js_bridge"
    );
}

// ---------------------------------------------------------------------------
// Test 8: Manifest init and reload round-trip
// ---------------------------------------------------------------------------

#[test]
fn test_manifest_init_round_trip() {
    let tmp = tempdir().unwrap();
    let dir = tmp.path().to_str().unwrap();

    // Init creates a file
    iseriser::manifest::init_manifest(dir).expect("init failed");

    let manifest_path = tmp.path().join("iseriser.toml");
    assert!(
        manifest_path.exists(),
        "iseriser.toml should exist after init"
    );

    // The generated file should be parseable
    let content = std::fs::read_to_string(&manifest_path).unwrap();
    let m = parse_manifest(&content).expect("generated manifest should parse");
    validate(&m).expect("generated manifest should validate");
}

// ---------------------------------------------------------------------------
// Test 9: Structural validation catches missing repo-name suffix
// ---------------------------------------------------------------------------

#[test]
fn test_structural_validation_repo_name_suffix() {
    let toml = r#"
[project]
name = "bad"
[language]
name = "Bad"
paradigm = "imperative"
type-system = "simple"
compilation-target = "native"
key-primitives = ["x"]
[output]
repo-name = "bad-tool"
github-org = "hyperpolymath"
description = "test"
"#;
    let m = parse_manifest(toml).unwrap();
    let err = validate(&m).unwrap_err();
    assert!(
        err.to_string().contains("iser"),
        "should require repo-name ending in 'iser'"
    );
}

// ---------------------------------------------------------------------------
// Test 10: `generate_all` pairs every -iser with its boj-server cartridge
// ---------------------------------------------------------------------------
//
// hyperpolymath/standards#90 asks that every new -iser carry the unified
// transaction-gated adapter and its SSE surface *by construction*. The
// cartridge is where that lives (iseriser PR #23 established the topology:
// the adapter belongs in `boj-server/cartridges/<iser>-mcp/`, never inside
// the -iser repo, where it has no FFI module to import). So the contract
// this test pins is: one `generate` produces both trees, side by side, with
// the gate and the SSE surface in the cartridge and neither in the repo.

#[test]
fn test_generate_all_emits_repo_and_cartridge_side_by_side() {
    let toml = make_toml(
        "Chapel",
        "imperative",
        "simple",
        "native",
        &["task", "locale", "domain"],
    );
    let m = parse_manifest(&toml).unwrap();
    validate(&m).unwrap();

    let tmp = tempdir().unwrap();
    let out = tmp.path().to_str().unwrap();
    let result = iseriser::codegen::generate_all(&m, out).expect("generate_all failed");
    assert!(result.is_success(), "{:?}", result.error_message());

    let repo = tmp.path().join("chapeliser");
    let cartridge = tmp.path().join("chapeliser-mcp");
    assert!(repo.is_dir(), "-iser repo was not written");
    assert!(cartridge.is_dir(), "cartridge was not written alongside it");

    // The cartridge carries the pattern ported from boj-server#73: the
    // exposure/transaction gate and the SSE surface, in the unified adapter.
    let adapter =
        std::fs::read_to_string(cartridge.join("adapter/chapeliser_adapter.zig")).unwrap();
    assert!(
        adapter.contains("text/event-stream"),
        "adapter has no SSE surface"
    );
    assert!(
        adapter.contains("fn exposureSatisfied("),
        "adapter has no transaction gate"
    );
    assert!(
        adapter.contains("TRANSACTION GATE"),
        "adapter does not gate before dispatch"
    );

    // The Idris2 side is the source-of-truth contract the Zig gate mirrors.
    let idr =
        std::fs::read_to_string(cartridge.join("abi/ChapeliserMcp/SafeChapeliser.idr")).unwrap();
    assert!(
        idr.contains("exposureSatisfied"),
        "cartridge ABI has no exposure contract"
    );

    // ...and none of it leaks into the -iser repo (PR #23 topology ruling).
    assert!(
        !repo.join("adapter").exists(),
        "adapter emitted into the repo"
    );

    // The repo's half of the pattern is the trigger that fires the cartridge.
    let regen =
        std::fs::read_to_string(repo.join(".github/workflows/chapeliser-regen.yml")).unwrap();
    assert!(regen.contains("/cartridge/chapeliser-mcp/invoke"));
}

// ---------------------------------------------------------------------------
// Test 11: `--no-cartridge` emits the repo alone
// ---------------------------------------------------------------------------

#[test]
fn test_generate_repo_only_skips_the_cartridge() {
    let toml = make_toml("Chapel", "imperative", "simple", "native", &["task"]);
    let m = parse_manifest(&toml).unwrap();
    validate(&m).unwrap();

    let tmp = tempdir().unwrap();
    let out = tmp.path().to_str().unwrap();
    let result = iseriser::codegen::generate_repo_only(&m, out).expect("generate_repo_only failed");
    assert!(result.is_success(), "{:?}", result.error_message());

    assert!(tmp.path().join("chapeliser").is_dir());
    assert!(
        !tmp.path().join("chapeliser-mcp").exists(),
        "cartridge emitted despite the repo-only path"
    );
}
