// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Template customizer.
//
// After the scaffold engine generates the base file set, the customizer
// applies language-specific modifications:
//
//   - Paradigm-specific Cargo features / dependencies
//   - Type-system-depth-dependent ABI proof richness
//   - Compilation-target-specific FFI bridge shape
//   - Extra files for specific targets (NIF boilerplate for BEAM, etc.)

use std::path::PathBuf;

use crate::abi::{CompilationTarget, GeneratedFile, LanguageModel, Paradigm};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Apply all language-specific customizations to the generated file set.
///
/// This mutates `files` in place: it may append new files and modify
/// existing file contents.
pub fn apply_customizations(model: &LanguageModel, files: &mut Vec<GeneratedFile>) {
    // 1. Add paradigm-specific extras
    apply_paradigm_extras(model, files);

    // 2. Add target-specific extras
    apply_target_extras(model, files);

    // 3. Add type-system-specific extras
    apply_type_system_extras(model, files);
}

// ---------------------------------------------------------------------------
// Paradigm customizations
// ---------------------------------------------------------------------------

/// Add paradigm-specific files and modifications.
fn apply_paradigm_extras(model: &LanguageModel, files: &mut Vec<GeneratedFile>) {
    match model.paradigm {
        Paradigm::Functional => {
            // Functional languages often benefit from ADT mapping utilities
            files.push(generate_adt_mapper(model));
        }
        Paradigm::Array => {
            // Array languages need bulk data transfer helpers
            files.push(generate_array_bridge(model));
        }
        Paradigm::Dataflow => {
            // Dataflow languages need streaming/channel utilities
            files.push(generate_dataflow_bridge(model));
        }
        Paradigm::Logic => {
            // Logic languages need unification/backtracking FFI
            files.push(generate_logic_bridge(model));
        }
        Paradigm::Imperative => {
            // Imperative is the baseline — no extra files needed
        }
    }
}

/// Generate an ADT (algebraic data type) mapping utility for functional languages.
fn generate_adt_mapper(model: &LanguageModel) -> GeneratedFile {
    let iser_name = model.iser_name();
    let content = format!(
        r#"// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// ADT mapping utilities for {iser_name}.
// Maps Rust enums/structs to {lang_name} algebraic data types.
// Generated by iseriser (functional paradigm customization).

/// Trait for types that can be mapped to {lang_name} ADTs.
pub trait ToAdt {{
    /// The {lang_name}-side type name.
    fn adt_name(&self) -> &str;
    /// Serialise to the {lang_name} wire format.
    fn to_wire(&self) -> Vec<u8>;
}}
"#,
        iser_name = iser_name,
        lang_name = model.name,
    );
    GeneratedFile {
        path: PathBuf::from("src/codegen/adt_mapper.rs"),
        content,
    }
}

/// Generate a bulk array transfer bridge for array/tensor languages.
fn generate_array_bridge(model: &LanguageModel) -> GeneratedFile {
    let iser_name = model.iser_name();
    let content = format!(
        r#"// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Array/tensor bridge for {iser_name}.
// Provides zero-copy bulk data transfer between Rust and {lang_name}.
// Generated by iseriser (array paradigm customization).

/// Descriptor for a multi-dimensional array passed across FFI.
#[repr(C)]
pub struct ArrayDescriptor {{
    /// Pointer to contiguous data.
    pub data: *const u8,
    /// Number of dimensions.
    pub ndim: u32,
    /// Shape (length of each dimension).
    pub shape: *const u64,
    /// Strides in bytes.
    pub strides: *const i64,
    /// Element size in bytes.
    pub element_size: u32,
}}
"#,
        iser_name = iser_name,
        lang_name = model.name,
    );
    GeneratedFile {
        path: PathBuf::from("src/codegen/array_bridge.rs"),
        content,
    }
}

/// Generate a dataflow/streaming bridge for reactive languages.
fn generate_dataflow_bridge(model: &LanguageModel) -> GeneratedFile {
    let iser_name = model.iser_name();
    let content = format!(
        r#"// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Dataflow bridge for {iser_name}.
// Provides streaming channel primitives for {lang_name} interop.
// Generated by iseriser (dataflow paradigm customization).

/// A channel endpoint for streaming data across the FFI boundary.
#[repr(C)]
pub struct Channel {{
    /// Opaque handle to the {lang_name}-side channel.
    pub handle: u64,
    /// Whether this endpoint is a producer (true) or consumer (false).
    pub is_producer: bool,
}}
"#,
        iser_name = iser_name,
        lang_name = model.name,
    );
    GeneratedFile {
        path: PathBuf::from("src/codegen/dataflow_bridge.rs"),
        content,
    }
}

/// Generate a logic/unification bridge for logic programming languages.
fn generate_logic_bridge(model: &LanguageModel) -> GeneratedFile {
    let iser_name = model.iser_name();
    let content = format!(
        r#"// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Logic bridge for {iser_name}.
// Provides unification/backtracking FFI primitives for {lang_name}.
// Generated by iseriser (logic paradigm customization).

/// A logic term passed across the FFI boundary.
#[repr(C)]
pub struct Term {{
    /// Tag: 0=atom, 1=variable, 2=compound.
    pub tag: u8,
    /// For atoms: the functor name.  For variables: the variable name.
    pub name: *const u8,
    /// Number of subterms (0 for atoms/variables).
    pub arity: u32,
}}
"#,
        iser_name = iser_name,
        lang_name = model.name,
    );
    GeneratedFile {
        path: PathBuf::from("src/codegen/logic_bridge.rs"),
        content,
    }
}

// ---------------------------------------------------------------------------
// Compilation target customizations
// ---------------------------------------------------------------------------

/// Add compilation-target-specific files.
fn apply_target_extras(model: &LanguageModel, files: &mut Vec<GeneratedFile>) {
    match model.compilation_target {
        CompilationTarget::Beam => {
            files.push(generate_beam_nif_boilerplate(model));
        }
        CompilationTarget::Jvm => {
            files.push(generate_jni_boilerplate(model));
        }
        CompilationTarget::Wasm => {
            files.push(generate_wasm_bindings(model));
        }
        CompilationTarget::Js => {
            files.push(generate_js_bridge(model));
        }
        CompilationTarget::Native | CompilationTarget::Interpreted | CompilationTarget::Gpu => {
            // Handled by the base scaffold
        }
    }
}

/// Generate BEAM NIF boilerplate for Erlang/Elixir/Gleam targets.
fn generate_beam_nif_boilerplate(model: &LanguageModel) -> GeneratedFile {
    let iser_name = model.iser_name();
    let content = format!(
        r#"// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// BEAM NIF boilerplate for {iser_name}.
// Generated by iseriser for {lang_name} (BEAM target).

/// NIF resource type registration placeholder.
/// The actual NIF implementation lives in the Zig FFI layer;
/// this module provides Rust-side type mappings.
pub struct NifResource {{
    pub handle: u64,
}}
"#,
        iser_name = iser_name,
        lang_name = model.name,
    );
    GeneratedFile {
        path: PathBuf::from("src/codegen/beam_nif.rs"),
        content,
    }
}

/// Generate JNI boilerplate for JVM targets.
fn generate_jni_boilerplate(model: &LanguageModel) -> GeneratedFile {
    let iser_name = model.iser_name();
    let content = format!(
        r#"// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// JNI boilerplate for {iser_name}.
// Generated by iseriser for {lang_name} (JVM target).

/// JNI environment wrapper placeholder.
pub struct JniEnv {{
    pub version: u32,
}}
"#,
        iser_name = iser_name,
        lang_name = model.name,
    );
    GeneratedFile {
        path: PathBuf::from("src/codegen/jni_bridge.rs"),
        content,
    }
}

/// Generate WASM bindings for WebAssembly targets.
fn generate_wasm_bindings(model: &LanguageModel) -> GeneratedFile {
    let iser_name = model.iser_name();
    let content = format!(
        r#"// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// WASM bindings for {iser_name}.
// Generated by iseriser for {lang_name} (WASM target).

/// WASM memory descriptor for cross-module data sharing.
#[repr(C)]
pub struct WasmMemory {{
    pub ptr: u32,
    pub len: u32,
}}
"#,
        iser_name = iser_name,
        lang_name = model.name,
    );
    GeneratedFile {
        path: PathBuf::from("src/codegen/wasm_bindings.rs"),
        content,
    }
}

/// Generate JavaScript FFI bridge for JS targets.
fn generate_js_bridge(model: &LanguageModel) -> GeneratedFile {
    let iser_name = model.iser_name();
    let content = format!(
        r#"// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// JavaScript bridge for {iser_name}.
// Generated by iseriser for {lang_name} (JS target).

/// JS value wrapper for FFI.
pub enum JsValue {{
    Null,
    Bool(bool),
    Number(f64),
    Str(String),
    Array(Vec<JsValue>),
}}
"#,
        iser_name = iser_name,
        lang_name = model.name,
    );
    GeneratedFile {
        path: PathBuf::from("src/codegen/js_bridge.rs"),
        content,
    }
}

// ---------------------------------------------------------------------------
// Type system customizations
// ---------------------------------------------------------------------------

/// Add type-system-specific files when the language has rich types.
fn apply_type_system_extras(model: &LanguageModel, files: &mut Vec<GeneratedFile>) {
    if model.needs_deep_abi_proofs() {
        files.push(generate_deep_proof_readme(model));
    }
}

/// Generate a README explaining the deep ABI proof strategy.
fn generate_deep_proof_readme(model: &LanguageModel) -> GeneratedFile {
    let iser_name = model.iser_name();
    let content = format!(
        r#"= {iser_name} Deep ABI Proofs

{lang_name} has a rich type system ({type_sys}), so this -iser generates
enhanced Idris2 ABI proofs that verify:

* Type correspondence between Rust and {lang_name} representations
* Ownership/linearity preservation across the FFI boundary
* Refinement contract propagation

See `src/interface/abi/Types.idr` for the formal definitions.
"#,
        iser_name = iser_name,
        lang_name = model.name,
        type_sys = model.type_system,
    );
    GeneratedFile {
        path: PathBuf::from("docs/deep-abi-proofs.adoc"),
        content,
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::abi::*;

    fn make_model(
        paradigm: Paradigm,
        target: CompilationTarget,
        type_sys: TypeSystemFeature,
    ) -> LanguageModel {
        LanguageModel {
            name: "TestLang".to_string(),
            paradigm,
            type_system: type_sys,
            compilation_target: target,
            key_primitives: vec!["prim1".to_string()],
        }
    }

    #[test]
    fn test_functional_adds_adt_mapper() {
        let model = make_model(
            Paradigm::Functional,
            CompilationTarget::Native,
            TypeSystemFeature::Algebraic,
        );
        let mut files = Vec::new();
        apply_customizations(&model, &mut files);
        assert!(
            files
                .iter()
                .any(|f| f.path.to_str().unwrap().contains("adt_mapper"))
        );
    }

    #[test]
    fn test_array_adds_array_bridge() {
        let model = make_model(
            Paradigm::Array,
            CompilationTarget::Native,
            TypeSystemFeature::ArrayTypes,
        );
        let mut files = Vec::new();
        apply_customizations(&model, &mut files);
        assert!(
            files
                .iter()
                .any(|f| f.path.to_str().unwrap().contains("array_bridge"))
        );
    }

    #[test]
    fn test_beam_adds_nif_boilerplate() {
        let model = make_model(
            Paradigm::Functional,
            CompilationTarget::Beam,
            TypeSystemFeature::Algebraic,
        );
        let mut files = Vec::new();
        apply_customizations(&model, &mut files);
        assert!(
            files
                .iter()
                .any(|f| f.path.to_str().unwrap().contains("beam_nif"))
        );
    }

    #[test]
    fn test_dependent_types_add_deep_proof_docs() {
        let model = make_model(
            Paradigm::Functional,
            CompilationTarget::Native,
            TypeSystemFeature::Dependent,
        );
        let mut files = Vec::new();
        apply_customizations(&model, &mut files);
        assert!(
            files
                .iter()
                .any(|f| f.path.to_str().unwrap().contains("deep-abi-proofs"))
        );
    }

    #[test]
    fn test_imperative_native_minimal_extras() {
        let model = make_model(
            Paradigm::Imperative,
            CompilationTarget::Native,
            TypeSystemFeature::Simple,
        );
        let mut files = Vec::new();
        apply_customizations(&model, &mut files);
        // Imperative + native + simple = no extras
        assert!(files.is_empty());
    }
}
